-- VHDL Entity lab4_lib.Full_Adder.symbol
--
-- Created:
--          by - mrn2.ews (dcl-l440-19.ews.illinois.edu)
--          at - 16:37:02 09/20/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Full_Adder IS
   PORT( 
      A    : IN     std_logic;
      B    : IN     std_logic;
      CIN  : IN     std_logic;
      COUT : OUT    std_logic;
      S    : OUT    std_logic
   );

-- Declarations

END Full_Adder ;

--
-- VHDL Architecture lab4_lib.Full_Adder.struct
--
-- Created:
--          by - mrn2.ews (dcl-l440-19.ews.illinois.edu)
--          at - 16:37:02 09/20/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lab4_lib;

ARCHITECTURE struct OF Full_Adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F     : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;


   -- Component Declarations
   COMPONENT my_xor
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : my_xor USE ENTITY lab4_lib.my_xor;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_2' of 'and'
   dout <= A AND B;

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   dout1 <= F AND CIN;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'or'
   COUT <= dout OR dout1;

   -- Instance port mappings.
   U_0 : my_xor
      PORT MAP (
         A => A,
         B => B,
         F => F
      );
   U_1 : my_xor
      PORT MAP (
         A => F,
         B => CIN,
         F => S
      );

END struct;
