-- VHDL Entity lab4_lib.my_xor.symbol
--
-- Created:
--          by - mrn2.ews (dcl-l440-19.ews.illinois.edu)
--          at - 16:00:20 09/20/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY my_xor IS
   PORT( 
      A : IN     std_logic;
      B : IN     std_logic;
      F : OUT    std_logic
   );

-- Declarations

END my_xor ;

--
-- VHDL Architecture lab4_lib.my_xor.struct
--
-- Created:
--          by - mrn2.ews (dcl-l440-19.ews.illinois.edu)
--          at - 16:00:20 09/20/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF my_xor IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'and'
   dout1 <= dout AND B;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'and'
   din1 <= A AND dout2;

   -- ModuleWare code(v1.9) for instance 'U_3' of 'inv'
   dout <= NOT(A);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'inv'
   dout2 <= NOT(B);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'or'
   F <= dout1 OR din1;

   -- Instance port mappings.

END struct;
