-- VHDL Entity lab6_lib.vm_circuit.symbol
--
-- Created:
--          by - mrn2.ews (gelib-4c-39.ews.illinois.edu)
--          at - 14:35:13 10/17/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY vm_circuit IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      A  : OUT    std_logic;
      P  : OUT    std_logic
   );

-- Declarations

END vm_circuit ;

--
-- VHDL Architecture lab6_lib.vm_circuit.struct
--
-- Created:
--          by - mrn2.ews (gelib-4c-39.ews.illinois.edu)
--          at - 14:35:14 10/17/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF vm_circuit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout   : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout10 : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout6  : std_logic;
   SIGNAL dout7  : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL dout9  : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout5 <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'inv'
   dout1 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_11' of 'inv'
   dout10 <= NOT(S0);

   -- ModuleWare code(v1.9) for instance 'U_0' of 'nand'
   dout <= NOT(S2 AND S1);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'nand'
   P <= NOT(dout7 AND dout9);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'nand'
   dout3 <= NOT(dout AND dout);

   -- ModuleWare code(v1.9) for instance 'U_6' of 'nand'
   dout2 <= NOT(dout1 AND S0);

   -- ModuleWare code(v1.9) for instance 'U_7' of 'nand'
   dout4 <= NOT(dout2 AND dout2);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'nor'
   dout9 <= NOT(dout8 OR dout8);

   -- ModuleWare code(v1.9) for instance 'U_8' of 'nor'
   A <= NOT(dout3 OR dout4);

   -- ModuleWare code(v1.9) for instance 'U_9' of 'nor'
   dout6 <= NOT(S2 OR dout5);

   -- ModuleWare code(v1.9) for instance 'U_10' of 'nor'
   dout7 <= NOT(dout6 OR dout6);

   -- ModuleWare code(v1.9) for instance 'U_12' of 'nor'
   dout8 <= NOT(dout1 OR dout10);

   -- Instance port mappings.

END struct;
