-- VHDL Entity lab6_lib.vm_circuit_beta.symbol
--
-- Created:
--          by - mrn2.ews (dcl-l440-19.ews.illinois.edu)
--          at - 15:13:14 10/04/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY vm_circuit_beta IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      A  : OUT    std_logic;
      P  : OUT    std_logic
   );

-- Declarations

END vm_circuit_beta ;

--
-- VHDL Architecture lab6_lib.vm_circuit_beta.struct
--
-- Created:
--          by - mrn2.ews (dcl-l440-19.ews.illinois.edu)
--          at - 15:13:14 10/04/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF vm_circuit_beta IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'and'
   dout6 <= S2 AND S0;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'and'
   A <= dout3 AND dout4;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'and'
   dout5 <= dout AND S1;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   dout <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'inv'
   dout1 <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'inv'
   dout2 <= NOT(S0);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'or'
   dout3 <= dout OR dout1;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'or'
   dout4 <= S2 OR dout2;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'or'
   P <= dout5 OR dout6;

   -- Instance port mappings.

END struct;
